export const phoneData = [
    {   
        id:'225',
        network:'	Technology	 GSM / HSPA / LTE',
        brand:'Motorola',
        name: 'Motorola Moto E13',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-e13-new.jpg',
        released: '2023, February 13',
        display: 'IPS LCD Size	6.5 inches, 102.0 cm2 (~82.8% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 13 (Go edition) Chipset	Unisoc T606 (12 nm) CPU	Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)',
        memory:{
            ram:2,
            rom:64,
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, f/2.2, (wide), 1.12µm, PDAF Features	LED flash, HDR, panorama Video	1080p@30fps',
        main_camera2:13,
        selfie_camera2:5,
        selfie_camera:'5 MP, f/2.4, (wide), 1/5", 1.12µm Video	1080p@30fps',
        features:'Accelerometer, proximity',
        communication:'WLAN	Wi-Fi 802.11 a/b/g/n/ac, dual-band Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable Charging	10W wired',
        description:'The Moto E13 follows the flat-frame design trend that most smartphones tend to sport these days. The frame, like the curved rear panel, is made of plastic. Motorola has tried giving the phone a premium look with a gradient frosted finish, which is something I really liked. I have the Aurora Green colour but if you want a more classic look, theres Cosmic Black and Creamy White colour options as well.',
        price:'7165',  
        battery2:5000, 
    },
    {   
        id:'226',
        network:'GSM / HSPA / LTE 2G bands	GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 3G bands	HSDPA 850 / 900 / 2100 4G bands	1, 3, 5, 8, 40, 41 Speed	HSPA, LTE',
        brand:'Xiaomi',
        name: 'Xiaomi Poco C51',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c51.jpg',
        released: '2023, April 13',
        display: 'IPS LCD, 400 nits (typ) Size	6.52 inches, 102.6 cm2 (~81.0% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~269 ppi density)',
        platform: 'Android 13 (Go edition), MIUI Chipset	Mediatek Helio G36 (12 nm) CPU	Octa-core (4x2.2 GHz Cortex-A53 & 4x1.7 GHz Cortex-A53)',
        memory:{
            ram:4,
            rom:64,
            cardslot:'NO'
        },
        main_camera2:8,
        selfie_camera2:5,
        main_camera:'8 MP, f/2.0, (wide)  0.08 MP (depth)  Features	Dual-LED flash, HDR  Video	1080p@30fps',
        selfie_camera:'5 MP, f/2.2  Video	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer',
        communication:'WLAN	Wi-Fi 802.11 b/g/n  Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable  Charging	10W wired',
        description:'As is often the case with entry-level smartphones, their designs tend to be very simple and theres usually not much to be said about its build quality. However, this is not the case with the Poco C51. Personally, I think the smartphone has a better design, grip, and build quality compared to its rivals. It has a polycarbonate back panel with a grainy texture which I felt was comfortable to hold even for long periods at a stretch. It offers good grip and the weight is distributed in such a way that it does not feel heavy in the hand, even though it weighs 19',
        price:'7075',  
        battery2:5000, 
    },
    {   
        id:'227',
        network:'GSM / HSPA / LTE',
        brand:'Samsung',
        name: 'Samsung Galaxy M12',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-sm-a125.jpg',
        released: '2021, February 05',
        display: 'PLS LCD, 90Hz Size	6.5 inches, 102.0 cm2 (~81.9% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 11',
        memory:{
            ram:4,
            rom:64,
            cardslot:'microSDXC'
        },
        main_camera2:48,
        selfie_camera2:8,
        main_camera:'48 MP, f/2.0, (wide), 1/2.0", 0.8µm, PDAF  5 MP, f/2.2, 123˚ (ultrawide)  2 MP, f/2.4, (macro)  2 MP, f/2.4, (depth)  Features	LED flash, panorama, HDRVideo	1080p@30fps',
        selfie_camera:'8 MP, f/2.2, (wide) Features	HDR Video	1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 6000 mAh, non-removable Charging	15W wired',
        description:'Samsung Galaxy M12 mobile was launched on 5th February 2021. The phone comes with a 6.50-inch touchscreen display offering a resolution of 720x1600 pixels and an aspect ratio of 20:9. Samsung Galaxy M12 is powered by an octa-core processor. It comes with 3GB, 4GB, 6GB of RAM. The Samsung Galaxy M12 runs Android and is powered by a 6000mAh battery',
        price:'12000',  
        battery2:6000, 
    },
    {   
        id:'228',
        network:'GSM / HSPA / LTE',
        brand:'Infinix',
        name: 'Infinix Smart 7',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-smart-7.jpg',
        released: '2023, February 09',
        display: 'IPS LCD, 500 nits Size	6.6 inches, 104.6 cm2 (~84.5% screen-to-body ratio) Resolution	720 x 1612 pixels, 20:9 ratio (~267 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:3,
            rom:'62GB',
            cardslot:'microSDXC'
        },
        main_camera2:13,
        selfie_camera2:5,
        main_camera:'13 MP, AF 0.3 MP, (depth) Features	Dual-LED flash, HDR, panorama Video	1080p@30fps',
        selfie_camera:'	5 MP Features	LED flash Video	720p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer, proximity',
        communication:'	Wi-Fi 802.11 a/b/g/n/ac, dual-band Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable Charging	10W wired',
        description:'The Infinix Smart 7 is available in a sole variant with 4GB of RAM and 64GB of storage. It comes in Azure Blue, Night Black and Emerald Green colour options. The smartphone is priced at Rs. 7,499 in India. The Infinix Smart 7 features a polycarbonate housing which quite frankly, is sturdy. At 207g, the smartphone definitely feels heavy. It has flat sides with the power key and volume buttons on the right and the SIM slot on the left. The Type-C charging port, microphone, speaker grille and headphone jack are all located at the bottom. ',
        price:'6599',   
        battery2:5000,
    },
    {   
        id:'229',
        network:'GSM / HSPA / LTE',
        brand:'Samsung',
        name: 'Samsung Galaxy F04',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f04-new.jpg',
        released: '2023, January 04',
        display: 'PLS LCD Size	6.5 inches, 102.0 cm2 (~81.8% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:4,
            rom:64,
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, f/2.2, (wide), AF 2 MP, f/2.4, (depth) Features	LED flash Video	1080p@30fps',
        selfie_camera:'5 MP, f/2.2 Video	Yes',
        features:'Accelerometer, proximity',
        communication:'Wi-Fi 802.11 b/g/n, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh',
        battery2:5000,
        description:'Samsung Galaxy F04 mobile was launched on 4th January 2023. The phone comes with a 6.50-inch touchscreen display offering a resolution of 720x1600 pixels (HD+). It comes with 4GB of RAM. The Samsung Galaxy F04 is powered by a 5000mAh battery.',
        price:'6500',   
    },
    {   
        id:'230',
        network:'GSM / HSPA / LTE',
        brand:'Xiaomi',
        name: 'Xiaomi Poco C50',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c50.jpg',
        released: '2023, January 03',
        display: 'IPS LCD, 400 nits Size	6.52 inches, 102.6 cm2 (~81.0% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~269 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:3,
            rom:32,
            cardslot:'microSDXC '
        },
        main_camera2:8,
        selfie_camera2:5,
        main_camera:'8 MP, f/2.0, (wide) 0.08 MP (depth) Features	Dual-LED flash, HDR Video	1080p@30fps',
        selfie_camera:'	5 MP, f/2.0 Video	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh',
        battery2:5000,
        description:'Poco C50 mobile was launched on 3rd January 2023. The phone comes with a 6.52-inch touchscreen display offering a resolution of 700x1600 pixels. The Poco C50 runs Android Go Edition and is powered by a 5000mAh battery. The Poco C50 supports proprietary fast charging.',
        price:'6200',   
    },
    {   
        id:'231',
        network:'GSM / HSPA / LTE',
        brand:'Infinix',
        name: 'Infinix Hot 9 Play',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-hot9-play.jpg',
        released: '2020, April 09',
        display: 'IPS LCD Size	6.82 inches, 110.5 cm2 (~82.4% screen-to-body ratio) Resolution	720 x 1640 pixels (~263 ppi density)',
        platform: 'Android 9.0 Pie',
        memory:{
            ram:3,
            rom:64,
            cardslot:'microSDXC'
        },
        main_camera2:13,
        main_camera:'13 MP, (wide), 1/3.1", 1.12µm, AF  QVGA (Low light sensor) Features	Triple-LED flash, panorama, HDRVideo	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 6000 mAh',
        battery2:6000,
        description:'The Infinix Hot 9 was recently launched in India, along with a variant called the Hot 9 Pro. These smartphones were both priced below Rs. 10000 at launch, but feature quad cameras and hole-punch displays. What caught my eye is the choice of processor. The Infinix Hot 9 packs in the same processor as the Infinix Hot 8, which raises a few questions. Is the Hot 9 a true upgrade, or has Infinix compromised too much to keep the price below Rs. 10000.',
        price:'7999',   
    },
    {
        name: 'Xiaomi Redmi Note 12 5G',
        id: '1',
        brand: 'Xiaomi',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/redmi-note-12-5g-international.jpg',
        released: '2023, January 11',
        display: 'AMOLED, 120Hz, 1200 nits (peak), 6.67 inches, 107.4 cm2 (~85.0% screen-to-body ratio), Corning Gorilla Glass 3' ,
        platform: 'Android 12, MIUI 14 (International), MIUI 13 (India), Qualcomm SM4375 Snapdragon 4 Gen 1 (6 nm)',
        memory:{
            ram:4,
            rom:128,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:48,
        selfie_camera2:13,
        main_camera:'48 MP, f/1.8, (wide), PDAF, 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm, 2 MP, f/2.4, (macro), v2 MP, f/2.4, (macro), 1080p@30fps',
        selfie_camera:'13 MP, f/2.5, (wide), 1/3.0", HDR, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band',
        battery:'Li-Po 5000 mAh, non-removable , 33W wired',
        price:'12998',
        battery2:5000,
        network:'5G',
        description:"With the 4G version of the most affordable Redmi Note 12 this year out of the way, it's time to take time to know the 5G alteration as well. The thing is, the Redmi Note 12 4G and Note 12 5G employ different hardware so the user experience might vary quite a bit. Its not just the 5G part.The most obvious difference is in the chipsets. The 4G has a Snapdragon 685 on board, while the 5G option has a Snapdragon 4 Gen 1 SoC. And contrary to our expectations, the latter seems to be more powerful in every aspect. And it better be, because the original, 5G-capable Redmi Note 12 asks almost €100 more."
    }
    ,
    
    {
        name: 'Xiaomi Redmi Note 12 Pro',
        brand: 'Xiaomi',
        id: '2',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro.jpg',
        released: '2022, November 01',
        display: 'OLED, 1B colors, 120Hz, Dolby Vision, HDR10+, 500 nits (typ), 900 nits (HBM), 6.67 inches, 107.4 cm2 (~86.7% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, MIUI 13, Mediatek MT6877V Dimensity 1080 (6 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:16,
        main_camera:'50 MP, f/1.9, 24mm (wide), 1/1.56", 1.0µm, PDAF, OIS , 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm 2 MP, f/2.4, (macro)',
        selfie_camera:'16 MP, f/2.5, (wide), 1/3.06", 1.0µm HDR 1080p@30/60fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 67W wired',
        price:'18891',
        battery2:5000,
        network:'5G',
        description:"The highlights of the mainstream Pro model include a Dolby Vision OLED, fast performance, a 50MP OIS primary camera, and fast 67W charging. This Redmi Note 12 Pro should be the cheapest smartphone to offer the complete Dolby package - Vision and Atmos.Indeed, the Redmi Note 12 Pro employs a 6.67-inch Dolby Vision OLED with 1B colors and 120Hz refresh rate. It sits on top of the Dimensity 1080 5G chipset, which should provide enough oomph for smooth gaming on a budget. And, as we've mentioned, the phone also features Dolby Atmos stereo speakers.There are three cameras on the back of the Redmi Note 12 Pro - a 50MP OIS primary, an 8MP ultrawide shooter, and a 2MP macro cam"
    }
    ,
    {
        name: 'Xiaomi Redmi Note 12 5G',
        brand: 'Xiaomi',
        id: '3',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/redmi-note-12-5g-international.jpg',
        released: '2023, January 11',
        display: 'AMOLED, 120Hz, 1200 nits (peak), 6.67 inches, 107.4 cm2 (~85.0% screen-to-body ratio), Corning Gorilla Glass 3' ,
        platform: '',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:48,
        selfie_camera2:13,
        main_camera:'48 MP, f/1.8, (wide), PDAF, 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm, 2 MP, f/2.4, (macro), v2 MP, f/2.4, (macro), 1080p@30fps',
        selfie_camera:'13 MP, f/2.5, (wide), 1/3.0", HDR, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band',
        battery:'Li-Po 5000 mAh, non-removable , 33W wired',
        price:'14998',
        battery2:5000,
        network:'5G',
        description:"The highlights of the mainstream Pro model include a Dolby Vision OLED, fast performance, a 50MP OIS primary camera, and fast 67W charging. This Redmi Note 12 Pro should be the cheapest smartphone to offer the complete Dolby package - Vision and Atmos.Indeed, the Redmi Note 12 Pro employs a 6.67-inch Dolby Vision OLED with 1B colors and 120Hz refresh rate. It sits on top of the Dimensity 1080 5G chipset, which should provide enough oomph for smooth gaming on a budget. And, as we've mentioned, the phone also features Dolby Atmos stereo speakers.There are three cameras on the back of the Redmi Note 12 Pro - a 50MP OIS primary, an 8MP ultrawide shooter, and a 2MP macro cam"
    }
    ,
    
    
    {
        name: 'Xiaomi Redmi Note 12 Pro',
        brand: 'Xiaomi',
        id: '4',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-12-pro.jpg',
        released: '2022, November 01',
        display: 'OLED, 1B colors, 120Hz, Dolby Vision, HDR10+, 500 nits (typ), 900 nits (HBM), 6.67 inches, 107.4 cm2 (~86.7% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, MIUI 13, Mediatek MT6877V Dimensity 1080 (6 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:16,
        main_camera:'50 MP, f/1.9, 24mm (wide), 1/1.56", 1.0µm, PDAF, OIS , 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm 2 MP, f/2.4, (macro)',
        selfie_camera:'16 MP, f/2.5, (wide), 1/3.06", 1.0µm HDR 1080p@30/60fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 67W wired',
        price:'21799',
        battery2:5000,
        network:'5G',
        description:"The highlights of the mainstream Pro model include a Dolby Vision OLED, fast performance, a 50MP OIS primary camera, and fast 67W charging. This Redmi Note 12 Pro should be the cheapest smartphone to offer the complete Dolby package - Vision and Atmos.Indeed, the Redmi Note 12 Pro employs a 6.67-inch Dolby Vision OLED with 1B colors and 120Hz refresh rate. It sits on top of the Dimensity 1080 5G chipset, which should provide enough oomph for smooth gaming on a budget. And, as we've mentioned, the phone also features Dolby Atmos stereo speakers.There are three cameras on the back of the Redmi Note 12 Pro - a 50MP OIS primary, an 8MP ultrawide shooter, and a 2MP macro cam"
    
    }
    ,
    {
        name: 'Samsung Galaxy S21 FE 5G',
        brand: 'Samsung',
        id: '5',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg',
        released: '2022, January 07',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.4 inches, 100.5 cm2 (~86.7% screen-to-body ratio), 080 x 2340 pixels, 19.5:9 ratio (~403 ppi density), orning Gorilla Glass Victus ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Qualcomm SM8350 Snapdragon 888 5G (5 nm) - Version 1',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'32860',
        battery2:4500,
        network:'5G',
        description:"Samsung has focused on three fan-favorite features for this Fan Edition - display, performance, and camera. And it has tried to give more of those for less, a job best suited for the flagship-killer kind. We surely are not calling it that, but the S21 FE does sound quite promising as an almost-there-flagship.The Galaxy S21 FE updates the display with the S21's screen panel. It offers a 6.4-inch Dynamic AMOLED 2X with native HDR10+ support and a 120Hz refresh rate. The Galaxy S20 FE's Super AMOLED had no HDR10 capabilities at launch, which was disappointing back then, but these were enabled later in 2021.Then there is performance - quite expectedly, the Galaxy S21 FE offers the same hardware as the rest of the S21 series - either the Snapdragon 888, or the Exynos 2100 chipset. But the chipset segmentation is reversed here - the international model is the one with the Snapdragon, while Samsung's silicon is limited to Australia (so far)."
    }
    ,
    
    {
        name: 'Samsung Galaxy S21 FE 5G',
        brand: 'Samsung',
        id: '6',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg',
        released: '2022, January 07',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.4 inches, 100.5 cm2 (~86.7% screen-to-body ratio), 080 x 2340 pixels, 19.5:9 ratio (~403 ppi density), orning Gorilla Glass Victus ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Qualcomm SM8350 Snapdragon 888 5G (5 nm) - Version 1',
        memory:{
            ram:8,
            rom:256,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'38860',
        battery2:4500,
        network:'5G',
        description:"Samsung has focused on three fan-favorite features for this Fan Edition - display, performance, and camera. And it has tried to give more of those for less, a job best suited for the flagship-killer kind. We surely are not calling it that, but the S21 FE does sound quite promising as an almost-there-flagship.The Galaxy S21 FE updates the display with the S21's screen panel. It offers a 6.4-inch Dynamic AMOLED 2X with native HDR10+ support and a 120Hz refresh rate. The Galaxy S20 FE's Super AMOLED had no HDR10 capabilities at launch, which was disappointing back then, but these were enabled later in 2021.Then there is performance - quite expectedly, the Galaxy S21 FE offers the same hardware as the rest of the S21 series - either the Snapdragon 888, or the Exynos 2100 chipset. But the chipset segmentation is reversed here - the international model is the one with the Snapdragon, while Samsung's silicon is limited to Australia (so far)."
    }
    ,
    
    {
        name: 'Samsung Galaxy S21 FE 5G',
        brand: 'Samsung',
        id: '7',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg',
        released: '2022, January 07',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.4 inches, 100.5 cm2 (~86.7% screen-to-body ratio), 080 x 2340 pixels, 19.5:9 ratio (~403 ppi density), orning Gorilla Glass Victus ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Qualcomm SM8350 Snapdragon 888 5G (5 nm) - Version 1',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'34860',
        battery2:4500,
        network:'5G',
        description:"Samsung has focused on three fan-favorite features for this Fan Edition - display, performance, and camera. And it has tried to give more of those for less, a job best suited for the flagship-killer kind. We surely are not calling it that, but the S21 FE does sound quite promising as an almost-there-flagship.The Galaxy S21 FE updates the display with the S21's screen panel. It offers a 6.4-inch Dynamic AMOLED 2X with native HDR10+ support and a 120Hz refresh rate. The Galaxy S20 FE's Super AMOLED had no HDR10 capabilities at launch, which was disappointing back then, but these were enabled later in 2021.Then there is performance - quite expectedly, the Galaxy S21 FE offers the same hardware as the rest of the S21 series - either the Snapdragon 888, or the Exynos 2100 chipset. But the chipset segmentation is reversed here - the international model is the one with the Snapdragon, while Samsung's silicon is limited to Australia (so far)."
    }
    ,
    
    {
        name: 'Xiaomi Redmi Note 11',
        brand: 'Xiaomi',
        id: '8',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-global.jpg',
        released: '2022, February 09',
        display: 'AMOLED, 90Hz, 700 nits, 1000 nits (peak), 6.43 inches, 99.8 cm2 (~84.5% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~409 ppi density), Corning Gorilla Glass 3' ,
        platform: 'Android 11, upgradable to Android 13, MIUI 14, Qualcomm SM6225 Snapdragon 680 4G (6 nm), Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver), Adreno 610',
        memory:{
            ram:4,
            rom:64,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'9899',
        battery2:4500,
        network:'4G',
        description: "This Redmi Note 11 starts at $180 for a 4/64GB unit (and this is if you missed the early bird deal) and goes up to $230 for a 6/128GB unit. That's a bit less than last year's vanilla Redmi Note 10, which is curious.Perhaps the reason for that is that not all of the changes are strictly upgrades over the last year's model. The Snapdragon 680 4G chipset for this year is definitely newer than the Snapdragon 678 in the Redmi Note 10 and is hence made on a much smaller and more efficient 6nm manufacturing process (compared to 11nm).Even though it's a newer chipset, the Adreno 610 GPU inside the Snapdragon 680 is a downgrade compared to the Adreno 612 inside last year's Snapdragon 678. The same goes for the camera DSP, which is limited to 1080p video capture. Yet another unfortunate case of a 2022 device dropping 4K recording due to the feature being dropped from the Snapdragon 680 and Snapdragon 695."
    }
    ,
    {
        name: 'Xiaomi Redmi Note 11',
        brand: 'Xiaomi',
        id: '9',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-global.jpg',
        released: '2022, February 09',
        display: 'AMOLED, 90Hz, 700 nits, 1000 nits (peak), 6.43 inches, 99.8 cm2 (~84.5% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~409 ppi density), Corning Gorilla Glass 3' ,
        platform: 'Android 11, upgradable to Android 13, MIUI 14, Qualcomm SM6225 Snapdragon 680 4G (6 nm), Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver), Adreno 610',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'12998',
        battery2:4500,
        network:'4G',
        description: "This Redmi Note 11 starts at $180 for a 4/64GB unit (and this is if you missed the early bird deal) and goes up to $230 for a 6/128GB unit. That's a bit less than last year's vanilla Redmi Note 10, which is curious.Perhaps the reason for that is that not all of the changes are strictly upgrades over the last year's model. The Snapdragon 680 4G chipset for this year is definitely newer than the Snapdragon 678 in the Redmi Note 10 and is hence made on a much smaller and more efficient 6nm manufacturing process (compared to 11nm).Even though it's a newer chipset, the Adreno 610 GPU inside the Snapdragon 680 is a downgrade compared to the Adreno 612 inside last year's Snapdragon 678. The same goes for the camera DSP, which is limited to 1080p video capture. Yet another unfortunate case of a 2022 device dropping 4K recording due to the feature being dropped from the Snapdragon 680 and Snapdragon 695."
    }
    ,
    {
        name: 'Samsung Galaxy S22 Ultra 5G',
        brand: 'Samsung',
        id: '10',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-ultra-5g.jpg',
        released: '2022, February 25',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 1750 nits (peak), 6.8 inches, 114.7 cm2 (~90.2% screen-to-body ratio), 1440 x 3088 pixels, 19.3:9 ratio (~500 ppi density), Corning Gorilla Glass Victus+ ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1,	Exynos 2200 (4 nm) - Europe',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:108,
        selfie_camera2:40,
        main_camera:'108 MP, f/1.8, 23mm (wide), 1/1.33", 0.8µm, PDAF, Laser AF, OIS 10 MP, f/4.9, 230mm (periscope telephoto), 1/3.52", 1.12µm, dual pixel PDAF, OIS, 10x optical zoom 10 MP, f/2.4, 70mm (telephoto), 1/3.52", 1.12µm, dual pixel PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF, Super Steady video ,LED flash, auto-HDR, panorama, 8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, stereo sound rec., gyro-EIS',
        selfie_camera:'40 MP, f/2.2, 26mm (wide), 1/2.82", 0.7µm, PDAF, Dual video call, Auto-HDR , 4K@30/60fps, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 5000 mAh, non-removable, 45W wired, PD3.0, 15W wireless, 4.5W reverse wireless',
        price:'80850',
        network:'5G',
        battery2:5000,
        description: "The S Pen fans will have little to complain about on the face of it. The S22 Ultra has the same stylus as the Note20 Ultra and, like a true Note, it has a silo for keeping the thing inside the phone - none of that carry-it-separately-until-you-inevitably-lose-it nonsense with the S21 Ultra. The significant improvements in latency also sound promising, not that the old one was bad.The camera crowd shouldn't be disappointed either. You're getting the same quad setup as the S21 Ultra (in principle, at least) and includes a couple of telephotos reaching all the way to 10x zoom, as well as an autofocusing ultrawide (that Samsung insists on keeping exclusive to the Ultra). That's in addition to the big-sensor nona-binning 108MP main camera, of course."
    }
    ,
    {
        name: 'Apple iPhone 14 Pro Max',
        brand: 'Apple',
        id: '11',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro-max-.jpg',
        released: '2022, September 16',
        display: 'LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM), 6.7 inches, 110.2 cm2 (~88.3% screen-to-body ratio), 1290 x 2796 pixels, 19.5:9 ratio (~460 ppi density), Ceramic Shield glass' ,
        platform: 'iOS 16, upgradable to iOS 17.1, Apple A16 Bionic (4 nm), Hexa-core (2x3.46 GHz Everest + 4x2.02 GHz Sawtooth), Apple GPU (5-core graphics)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:48,
        selfie_camera2:12,
        main_camera:'48 MP, f/1.8, 24mm (wide), 1/1.28", 1.22µm, dual pixel PDAF, sensor-shift OIS 12 MP, f/2.8, 77mm (telephoto), 1/3.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF, TOF 3D LiDAR scanner (depth), Dual-LED dual-tone flash, HDR (photo/panorama), 4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 10-bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode (4K@24/30fps), stereo sound rec.',
        selfie_camera:'12 MP, f/1.9, 23mm (wide), 1/3.6", PDAF, OIS SL 3D, (depth/biometrics sensor), HDR, Cinematic mode (4K@24/30fps), 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS',
        features:'Face ID, accelerometer, gyro, proximity, compass, barometer Ultra Wideband (UWB) support Emergency SOS via satellite (SMS sending/receiving)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
        battery:'Li-Ion 4323 mAh, non-removable (16.68 Wh), Wired, PD2.0, 50% in 30 min (advertised) 15W wireless (MagSafe) 7.5W wireless (Qi)',
        price:'139900',
        network:'5G',
        battery2:4323,
        description:"The best iPhone ever, version 2022, size XL - we have the iPhone 14 Pro Max. The list of novelties this year includes the notch morphing into a pill, the introduction of an Always-On display, and an all-new primary camera - and while you can get all of that on the 14 Pro, the extra screen estate and longevity coupled with the Max's 'ultimate' status mean it has a market niche of its own.Late to yet another party, Apple finally joins virtually every other manufacturer and introduces a camera with a Quad Bayer type sensor - the specs on the 48MP main unit.In a similar vein is the Always-On display - a software feature only made possible now in Apple's world thanks to LTPO displays being able to ramp down to 1Hz refresh rate."
    }
    ,
    {
        name: 'Apple iPhone 14 Pro Max',
        brand: 'Apple',
        id: '12',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro-max-.jpg',
        released: '2022, September 16',
        display: 'LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM), 6.7 inches, 110.2 cm2 (~88.3% screen-to-body ratio), 1290 x 2796 pixels, 19.5:9 ratio (~460 ppi density), Ceramic Shield glass' ,
        platform: 'iOS 16, upgradable to iOS 17.1, Apple A16 Bionic (4 nm), Hexa-core (2x3.46 GHz Everest + 4x2.02 GHz Sawtooth), Apple GPU (5-core graphics)',
        memory:{
            ram:6,
            rom:256,
            cardslot:'No'
        },
        main_camera2:48,
        selfie_camera2:12,
        main_camera:'48 MP, f/1.8, 24mm (wide), 1/1.28", 1.22µm, dual pixel PDAF, sensor-shift OIS 12 MP, f/2.8, 77mm (telephoto), 1/3.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF, TOF 3D LiDAR scanner (depth), Dual-LED dual-tone flash, HDR (photo/panorama), 4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 10-bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode (4K@24/30fps), stereo sound rec.',
        selfie_camera:'12 MP, f/1.9, 23mm (wide), 1/3.6", PDAF, OIS SL 3D, (depth/biometrics sensor), HDR, Cinematic mode (4K@24/30fps), 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS',
        features:'Face ID, accelerometer, gyro, proximity, compass, barometer Ultra Wideband (UWB) support Emergency SOS via satellite (SMS sending/receiving)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
        battery:'Li-Ion 4323 mAh, non-removable (16.68 Wh), Wired, PD2.0, 50% in 30 min (advertised) 15W wireless (MagSafe) 7.5W wireless (Qi)',
        price:'149900',
        network:'5G',
        battery2:4342,
        description:"The best iPhone ever, version 2022, size XL - we have the iPhone 14 Pro Max. The list of novelties this year includes the notch morphing into a pill, the introduction of an Always-On display, and an all-new primary camera - and while you can get all of that on the 14 Pro, the extra screen estate and longevity coupled with the Max's 'ultimate' status mean it has a market niche of its own.Late to yet another party, Apple finally joins virtually every other manufacturer and introduces a camera with a Quad Bayer type sensor - the specs on the 48MP main unit.In a similar vein is the Always-On display - a software feature only made possible now in Apple's world thanks to LTPO displays being able to ramp down to 1Hz refresh rate."
    },
    
    {
        name: 'Samsung Galaxy A13',
        brand: 'Samsung',
        id: '13',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13.jpg',
        released: '2022, March 23',
        display: 'PLS LCD, 6.6 inches, 104.9 cm2 (~83.2% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Exynos 850 (8nm)',
        memory:{
            ram:'3 GB',
            rom:'32 GB',
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, (wide), PDAF, 5 MP, f/2.2, 123˚ (ultrawide), 1/5", 1.12µm, 2 MP, f/2.4, (macro), 2 MP, f/2.4, (depth), LED flash, panorama, HDR, 1080p@30fps',
        selfie_camera:'8 MP, f/2.2, (wide), 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, compass Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 15W wired',
        price:'11998',
        battery2:5000,
        network:'4G',
        description:"The Galaxy A13 is one of the newest entry-level phones joining the Galaxy A family. We have the 4G version for review, which is already selling in India and Europe. There is a Galaxy A13 5G as well, which upgrades to a 90Hz screen and a MediaTek Dimensity 700 chipset, but is otherwise quite similar to our 4G version.It should be noted that the Galaxy A13 is actually not the lowest entry into the Galaxy A family, as it still sits above the Galaxy A03. Samsung has really been fleshing out its lineup lately. Unfortunately, that also means we end up with a large number of very similar devices.The Galaxy A13's body is nearly identical to the A13 5G, though it does get Gorilla Glass 5 display protection like the Galaxy A23. Also the same size 6.6 PLS LCD, though at 60Hz, unlike the A13 5G and A23, both of which can do 90Hz."
    }
    ,
    {
        name: 'Samsung Galaxy A13',
        brand: 'Samsung',
        id: '14',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a13.jpg',
        released: '2022, March 23',
        display: 'Super AMOLED, 120Hz, 800 nits (HBM), 	6.5 inches, 102.0 cm2 (~85.4% screen-to-body ratio), 	1080 x 2400 pixels, 20:9 ratio (~405 ppi density), 	Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Exynos 1280 (5 nm)',
        memory:{
            ram:4,
            rom:128,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, (wide), PDAF, 5 MP, f/2.2, 123˚ (ultrawide), 1/5", 1.12µm, 2 MP, f/2.4, (macro), 2 MP, f/2.4, (depth), LED flash, panorama, HDR, 1080p@30fps',
        selfie_camera:'8 MP, f/2.2, (wide), 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, compass Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 15W wired',
        price:'11998',
        battery2:5000,
        network:'4G',
        description:"The Galaxy A13 is one of the newest entry-level phones joining the Galaxy A family. We have the 4G version for review, which is already selling in India and Europe. There is a Galaxy A13 5G as well, which upgrades to a 90Hz screen and a MediaTek Dimensity 700 chipset, but is otherwise quite similar to our 4G version.It should be noted that the Galaxy A13 is actually not the lowest entry into the Galaxy A family, as it still sits above the Galaxy A03. Samsung has really been fleshing out its lineup lately. Unfortunately, that also means we end up with a large number of very similar devices.The Galaxy A13's body is nearly identical to the A13 5G, though it does get Gorilla Glass 5 display protection like the Galaxy A23. Also the same size 6.6 cm PLS LCD, though at 60Hz, unlike the A13 5G and A23, both of which can do 90Hz."
    },
    
    {
        name: 'Samsung Galaxy A53',
        brand: 'Samsung',
        id: '15',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a53-5g-.jpg',
        released: '2022, March 24',
        display: 'PLS LCD, 6.6 inches, 104.9 cm2 (~83.2% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Exynos 850 (8nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:64,
        selfie_camera2:32,
        main_camera:'64 MP, f/1.8, 26mm (wide), 0.8µm, PDAF, OIS12 MP, f/2.2, 123˚ (ultrawide), 1.12µm5 MP, f/2.4, (macro)5 MP, f/2.4, (depth)LED flash, panorama, HDR4K@30fps, 1080p@30/60fps; gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm, HDR, 4K@30fps, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, compass, barometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable 25W wired',
        price:'30990',
        network:'5G',
        battery2:5000,
        description:"First up - the straight-up positive change - the A53 5G has a larger 5000mAh battery than its predecessor. There is also a brand new chipset made by Samsung - the Exynos 1280. A modern 5nm part, still not officially present or detailed on Samsung's semiconductor website, but very much already in the wild and looking intriguing with a 2x2.4 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55 CPU configuration, a Mali-G68 GPU and arguably even more versatile 5G setup than the Snapdragon 778G 5G inside the A52s 5G.On the flip side, there are some notable downgrades in the A53 5G as well. For one, it lacks the 3.5mm audio jack of its predecessor. It is also missing Wi-Fi 6 support. Though, it does offer slightly newer Bluetooth 5.1.Other than this, the A53 5G is pretty much identical both in terms of specs and design to its predecessor. Even though, technically, it has shrunk down some in physical size, all the while keeping its display diagonal and weight unchanged. So, you are essentially getting smaller display bezels and a larger battery for 'free'. Not counting the 3.5mm jack, that is."
    
    },
    
    {
        name: 'Samsung Galaxy A53',
        brand: 'Samsung',
        id: '16',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a53-5g-.jpg',
        released: '2022, March 24',
        display: 'PLS LCD, 6.6 inches, 104.9 cm2 (~83.2% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Exynos 850 (8nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:64,
        selfie_camera2:32,
        main_camera:'64 MP, f/1.8, 26mm (wide), 0.8µm, PDAF, OIS12 MP, f/2.2, 123˚ (ultrawide), 1.12µm5 MP, f/2.4, (macro)5 MP, f/2.4, (depth)LED flash, panorama, HDR4K@30fps, 1080p@30/60fps; gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.8", 0.8µm, HDR, 4K@30fps, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, compass, barometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable 25W wired',
        price:'28998',
        network:'5G',
        battery2:5000,
        description:"First up - the straight-up positive change - the A53 5G has a larger 5000mAh battery than its predecessor. There is also a brand new chipset made by Samsung - the Exynos 1280. A modern 5nm part, still not officially present or detailed on Samsung's semiconductor website, but very much already in the wild and looking intriguing with a 2x2.4 GHz Cortex-A78 & 6x2.0 GHz Cortex-A55 CPU configuration, a Mali-G68 GPU and arguably even more versatile 5G setup than the Snapdragon 778G 5G inside the A52s 5G.On the flip side, there are some notable downgrades in the A53 5G as well. For one, it lacks the 3.5mm audio jack of its predecessor. It is also missing Wi-Fi 6 support. Though, it does offer slightly newer Bluetooth 5.1.Other than this, the A53 5G is pretty much identical both in terms of specs and design to its predecessor. Even though, technically, it has shrunk down some in physical size, all the while keeping its display diagonal and weight unchanged. So, you are essentially getting smaller display bezels and a larger battery for 'free' . Not counting the 3.5mm jack, that is."
    
    },
    
    {
        name: 'Samsung Galaxy A23',
        brand: 'Samsung',
        id: '17',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23.jpg',
        released: '2022, March 25',
        display: 'PLS LCD, 90Hz, 6.6 inches, 104.9 cm2 (~82.5% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5, Qualcomm SM6225 Snapdragon 680 4G (6 nm), Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver), Adreno 610',
        memory:{
            ram:8,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, (wide), PDAF, OIS 5 MP, f/2.2, 123˚ (ultrawide), 1/5", 1.12µm 2 MP, f/2.4, (macro) 2 MP, f/2.4, (depth)',
        selfie_camera:'8 MP, f/2.2, (wide), 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 25W wired',
        price:'22998',
        network:'5G',
        battery2:5000,
        description:"The Snapdragon 680 SoC powering the device is a recent one with fairly capable CPU, which offers a substantial upgrade over older Snapdragon 6xx chipsets. That's not to say there aren't some considerable drawbacks of the said platform, including the lack of 4K video recording and 5G connectivity. Then again, some of the said issues plague current mid-range smartphone alternatives using the Snapdragon 6xx series in 2022.Other than that, the Galaxy A23 shapes up to be a decent budget solution with a big 5000 mAh battery, competitive 25W fast charging (with a separate charger) over Power Delivery, Gorilla Glass 5 protection on the front and the fan-favorite microSD card slot. The Galaxy A23 is also launching with the latest Android 12 and Samsung's One UI 4.1 out of the box, which isn't a given with low-end phones."
    },
    
    {
        name: 'Samsung Galaxy A23',
        brand: 'Samsung',
        id: '18',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a23.jpg',
        released: '2022, March 25',
        display: 'PLS LCD, 90Hz, 6.6 inches, 104.9 cm2 (~82.5% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5, Qualcomm SM6225 Snapdragon 680 4G (6 nm), Octa-core (4x2.4 GHz Kryo 265 Gold & 4x1.9 GHz Kryo 265 Silver), Adreno 610',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, (wide), PDAF, OIS 5 MP, f/2.2, 123˚ (ultrawide), 1/5", 1.12µm 2 MP, f/2.4, (macro) 2 MP, f/2.4, (depth)',
        selfie_camera:'8 MP, f/2.2, (wide), 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 25W wired',
        price:'20998',
        battery2:5000,
        network:'5G',
        description:"The Snapdragon 680 SoC powering the device is a recent one with fairly capable CPU, which offers a substantial upgrade over older Snapdragon 6xx chipsets. That's not to say there aren't some considerable drawbacks of the said platform, including the lack of 4K video recording and 5G connectivity. Then again, some of the said issues plague current mid-range smartphone alternatives using the Snapdragon 6xx series in 2022.Other than that, the Galaxy A23 shapes up to be a decent budget solution with a big 5000 mAh battery, competitive 25W fast charging (with a separate charger) over Power Delivery, Gorilla Glass 5 protection on the front and the fan-favorite microSD card slot. The Galaxy A23 is also launching with the latest Android 12 and Samsung's One UI 4.1 out of the box, which isn't a given with low-end phones."
    },
    
    {
        name: 'Google Pixel 6a',
        brand: 'Google',
        id: '19',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6a.jpg',
        released: '2022, July 21',
        display: 'OLED, HDR, 6.1 inches, 90.7 cm2 (~83.0% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~429 ppi density), Corning Gorilla Glass 3' ,
        platform: 'Android 12, upgradable to Android 14, Google Tensor (5 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12.2,
        selfie_camera2:8,
        main_camera:'12.2 MP, f/1.7, 27mm, (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS, 12 MP, f/2.2, 17mm, 114˚ (ultrawide), 1.25µm, Dual-LED flash, Pixel Shift, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/120/240fps; gyro-EIS, OIS',
        selfie_camera:'8 MP, f/2.0, 24mm (wide), 1.12µm, Auto-HDR, panorama, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4410 mAh, non-removable, 18W wired, PD3.0',
        price:'30998',
        network:'5G',
        battery2:4410,
        description:"For the past three years Google has attempted to repackage its flagships phones into A Series phones that capture the Pixel essence at a far more attractive price point. The Google Pixel 6a even got the same custom Tensor chipset as the more expensive Pixels, further sweetening the deal.The Pixel 6a is notably compact with its 6.1-inch OLED screen and far lighter at 178g (vs 207g for the Pixel 6). It perfectly captures the design, look, and feel of the more expensive Pixel 6 and Pixel 6 Pro while strategically shaving costs down in places that doesn't have a big impact on usability.Google Pixel 6a review.The Pixel 6a doesn't have a charger in the box - a change that came with the Pixel 6 and 6 Pro. Google also axed the headphone jack in a first for the Pixel A Series.The Pixel 6a's camera is the tried-and-true Sony IMX 363 sensor, the same one that's been used since the Google Pixel 2. Google only stopped using it on its premium Pixels this year, so we probably shouldn't be surprised that the 6a didn't get a different sensor. And we might still see the aging sensor up its performance when paired with the Google Tensor."
    },
    
    {
        name: 'Apple iPhone 14',
        brand: 'Apple',
        id: '20',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg',
        released: '2022, September 16',
        display: 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak), 6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio), 1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density), Ceramic Shield glass' ,
        platform: 'iOS 16, upgradable to iOS 17.1, Apple A15 Bionic (5 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:12,
        main_camera:'12 MP, f/1.5, 26mm (wide), 1/1.7", 1.9µm, dual pixel PDAF, sensor-shift , 12 MP, f/2.4, 13mm, 120˚ (ultrawide), Dual-LED dual-tone flash, HDR (photo/panorama), 4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, HDR, Dolby Vision HDR (up to 60fps), Cinematic mode (4K@30fps), stereo sound rec.',
        selfie_camera:'12 MP, f/1.9, 23mm (wide), 1/3.6", PDAF, SL 3D, (depth/biometrics sensor), HDR, Cinematic mode (4K@30fps), 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS',
        features:'Face ID, accelerometer, gyro, proximity, compass, barometer, Ultra Wideband (UWB) support, Emergency SOS via satellite (SMS sending/receiving)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 3279 mAh, non-removable (12.68 Wh), Wired, PD2.0, 50% in 30 min (advertised)',
        price:'56998',
        battery2:3279,
        network:'5G',
        description:"The new iPhone 14 sort of fits into this category of product. Just sort of, though, since Apple has redesigned the internals quite a bit to facilitate easier repairability, among other things. Plus, you do get new cameras and a few other new features. Externally, though, the iPhone 14 is essentially the same as the iPhone 13, and so is the core experience these devices offer. If Apple still did 's' models in their naming scheme, the iPhone 14 would probably be the iPhone 13s.The vanilla iPhone 14 even starts at $799 in the US, just like its predecessor, so it occupies the same segment and fills the same shoes if it were. That said, most markets outside the US have a price hike on the iPhone 14, and the iPhone 13 has come down in price since its launch. Even in the US, it is now $100 or so cheaper"
    },
    
    {
        name: 'Xiaomi Redmi Note 11 Pro',
        brand: 'Xiaomi',
        id: '21',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-pro-global.jpg',
        released: '2022, February 18',
        display: 'Super AMOLED, 120Hz, 700 nits, 1200 nits (peak), 6.67 inches, 107.4 cm2 (~86.0% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 11, MIUI 13, Mediatek Helio G96 (12 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:108,
        selfie_camera2:16,
        main_camera:'108 MP, f/1.9, 26mm (wide), 1/1.52", 0.7µm, PDAF, 8 MP, f/2.2, 118˚ (ultrawide), 2 MP, f/2.4, (macro), 2 MP, f/2.4, (depth), LED flash, HDR, panorama, 1080p@30fps',
        selfie_camera:'16 MP, f/2.5, (wide), 1/3.06" 1.0µm, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass, Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 67W wired',
        price:'21499',
        battery2:5000,
        network:'5G',
    },
    
    {
        name: 'Xiaomi Redmi Note 11 Pro',
        brand: 'Xiaomi',
        id: '22',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-11-pro-global.jpg',
        released: '2022, February 18',
        display: 'Super AMOLED, 120Hz, 700 nits, 1200 nits (peak), 6.67 inches, 107.4 cm2 (~86.0% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 11, MIUI 13, Mediatek Helio G96 (12 nm)',
        memory:{
            ram:8,
            rom:256,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:108,
        selfie_camera2:16,
        main_camera:'108 MP, f/1.9, 26mm (wide), 1/1.52", 0.7µm, PDAF, 8 MP, f/2.2, 118˚ (ultrawide), 2 MP, f/2.4, (macro), 2 MP, f/2.4, (depth), LED flash, HDR, panorama, 1080p@30fps',
        selfie_camera:'16 MP, f/2.5, (wide), 1/3.06" 1.0µm, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass, Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 67W wired',
        price:'28498',
        battery2:5000,
        network:'5G',
    },
    
    {
        name: 'Google Pixel 7',
        brand: 'Google',
        id: '23',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel7-new.jpg',
        released: '2022, October 13',
        display: 'AMOLED, 90Hz, HDR10+, 1000 nits (HBM), 1400 nits (peak), 6.3 inches, 96.7 cm2 (~84.9% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~416 ppi density), Corning Gorilla Glass Victus' ,
        platform: 'Android 13, upgradable to Android 14, Google Tensor G2 (5 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:10.8,
        main_camera:'50 MP, f/1.9, 25mm (wide), 1/1.31", 1.2µm, dual pixel PDAF, Laser AF, OIS, 12 MP, f/2.2, 114˚ (ultrawide), 1/2.9", 1.25µm, Dual-LED flash, Pixel Shift, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/120/240fps; gyro-EIS, OIS, 10-bit HDR',
        selfie_camera:'10.8 MP, f/2.2, 21mm (ultrawide), 1/3.1", 1.22µm, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, tri-band, Wi-Fi Direct',
        battery:'Li-Ion 4355 mAh, non-removable, 20W wired',
        price:'42998',
        network:'5G',
        battery2:4355,
        description:"On the surface, the Pixel 7 and 7 Pro aren't much different from the Pixel 6 series while introducing some small but notable upgrades. Maybe that's part of the reason why we think the 7th generation has a good chance of winning over new fans around the globe. Although 'the globe' might not be the best choice of words given the limited availability as usual.The Pixel 7 offers a few key improvements over its predecessor, the Pixel 6. It's now running on an improved Google Tensor G2 chip with better AI capabilities, Gorilla Glass Victus build all-around, a better selfie camera and a smaller display. As a result, the Pixel 7 is slightly smaller than the Pixel 6, which is a clear indication that Google is aiming for the compact flagship niche. And although smaller, the Pixel 7's display is considerably brighter.The camera setup on the back remains unchanged. We've got a big 50MP sensor doing the heavy lifting and a 12MP ultrawide camera helping out. There's still no telephoto camera, but to be fair, that's a rare find in the compact flagship class. Still, Google promises better image processing and improved overall camera quality through machine learning algorithms and better ISP capabilities."
    },
    
    {
        name: 'Infinix Zero 5G',
        brand: 'Infinix',
        id: '24',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-zero-5g.jpg',
        released: '2022, March 03',
        display: 'IPS LCD, 120Hz, 500 nits (peak), 6.78 inches, 113.7 cm2 (~88.1% screen-to-body ratio), 1080 x 2460 pixels (~388 ppi density)' ,
        platform: 'Android 11, upgradable to Android 12, XOS 10.6, Mediatek MT6877 Dimensity 900 (6 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:48,
        selfie_camera2:16,
        main_camera:'48 MP, f/1.8, 26mm (wide), 1/2.0", 0.8µm, PDAF, 13 MP, f/2.5, 50mm (telephoto), 1/3.1", 1.12µm, PDAF, 2x optical zoom, 2 MP, Quad-LED flash, HDR, panorama, 4K@30fps, 1080p@30/60fps',
        selfie_camera:'16 MP, f/2.0, (wide), 1/2.76", 1.12µm, Dual-LED flash, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 33W wired',
        price:'19999',
        network:'5G',
        battery2:5000,
        description: "The Infinix Zero 5G is a cutting-edge smartphone that brings blazing-fast 5G connectivity to the palm of your hand. This device is designed for users who demand the utmost in performance, speed, and versatility, the device features a stunning AMOLED display, providing vibrant and sharp visuals with deep blacks. This Full HD+ (or higher) screen is perfect for streaming your favorite content, playing games, or browsing the web. The smartphone's camera system is versatile, with a high-resolution primary camera, an ultra-wide-angle lens, and a telephoto lens, ensuring that you can capture incredible photos and videos in any situation. The selfie camera is also of exceptional quality."
    },
    
    {
        name: 'vivo Y16',
        brand: 'vivo',
        id: '25',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/vivo-y16.jpg',
        released: '2022, September 01',
        display: 'IPS LCD, 6.51 inches, 102.3 cm2 (~82.5% screen-to-body ratio), 720 x 1600 pixels, 20:9 ratio (~270 ppi density)' ,
        platform: 'Android 12, Funtouch 12, Mediatek MT6765 Helio P35 (12nm)',
        memory:{
            ram:'3 GB',
            rom:'32 GB',
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:13,
        selfie_camera2:5,
        main_camera:'13 MP, f/2.2, (wide), PDAF, 2 MP, f/2.4, (macro), LED flash, 1080p@30fps',
        selfie_camera:'5 MP, f/2.2, (wide)',
        features:'Fingerprint (side-mounted), accelerometer, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band',
        battery:'Li-Po 5000 mAh, non-removable, 10W wired',
        price:'11999',
        network:'4G',
        battery2:5000,
        description: "he Vivo Y16 is a mid-range smartphone designed to cater to users who seek a solid smartphone experience without breaking the bank, One of the standout features of the Vivo Y16 is its camera system. The device is equipped with a triple-camera setup on the rear, allowing users to capture high-quality photos and videos. The primary camera offers sharp and vibrant images, while additional lenses, such as an ultra-wide-angle or macro lens, enhance versatility. The front-facing camera is ideal for selfies and video calls, delivering decent image quality. One of the standout features of the Vivo Y16 is its camera system. The device is equipped with a triple-camera setup on the rear, allowing users to capture high-quality photos and videos. The primary camera offers sharp and vibrant images, while additional lenses, such as an ultra-wide-angle or macro lens, enhance versatility. The front-facing camera is ideal for selfies and video calls, delivering decent image quality."
    },
    
    {
        name: 'Samsung Galaxy M33',
        brand: 'Samsung',
        id: '26',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m33.jpg',
        released: '2022, April 08',
        display: 'TFT LCD, 120Hz, 6.6 inches, 104.9 cm2 (~82.5% screen-to-body ratio), 1080 x 2408 pixels, 20:9 ratio (~400 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, One UI 4.1, Exynos 1280 (5 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, (wide), PDAF, 5 MP, f/2.2, 123˚ (ultrawide), 2 MP, f/2.4, (depth), 2 MP, f/2.4, (macro), LED flash, panorama, HDR, 4K@30fps, 1080p@30fps',
        selfie_camera:'8 MP, f/2.2, (wide), 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, Virtual Proximity Sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band',
        battery:'Li-Ion 5000 mAh, non-removable - International, Li-Ion 6000 mAh, non-removable - India, 25W wired',
        price:'19990',
        network:'5G',
        battery2:5000,
        dsecription: "The Samsung Galaxy M33 is a mid-range smartphone designed to offer a well-rounded and affordable mobile experience, the Samsung Galaxy M33 is expected to be powered by a capable processor, possibly from Samsung's Exynos series or another reputable manufacturer, ensuring smooth and efficient performance. It would likely offer multiple RAM and storage configurations to suit different user requirements. esign-wise, the Samsung Galaxy M33 is likely to feature a modern and sleek appearance, with a focus on both aesthetics and ergonomics. It would be comfortable to hold and use, with attention to build quality and materials, The device would run on the latest version of Android with Samsung's One UI skin, offering a user-friendly and customizable interface."
    },
    
    {
        name: 'OnePlus Nord CE 2 Lite 5G',
        brand: 'OnePlus',
        id: '27',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-nord-ce-2-lite-5g-0.jpg',
        released: '2022, April 30',
        display: 'IPS LCD, 120Hz, 6.59 inches, 104.5 cm2 (~84.1% screen-to-body ratio), 1080 x 2412 pixels, 20:9 ratio (~401 ppi density)' ,
        platform: 'Android 12, upgradable to Android 13, OxygenOS 13, Qualcomm SM6375 Snapdragon 695 5G (6 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'microSDXC (uses shared SIM slot)'
        },
        main_camera2:64,
        selfie_camera2:16,
        main_camera:'64 MP, f/1.7, 26mm (wide), 0.7µm, PDAF, 2 MP, f/2.4, (macro), 2 MP, f/2.4, (depth), LED flash, HDR, panorama, 1080p@30fps',
        selfie_camera:'16 MP, f/2.0, (wide), 1/3.0", 1.0µm, HDR, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 33W wired',
        price:'17109',
        network:'5G',
        battery2:5000,
        description: "The OnePlus Nord CE 2 Lite 5G is a mid-range smartphone that combines impressive performance, 5G connectivity, and a focus on delivering exceptional value to consumers. It follows in the footsteps of its predecessor, the OnePlus Nord CE, with some notable upgrades. t the heart of the OnePlus Nord CE 2 Lite 5G is a capable processor, which ensures smooth multitasking, quick app launches, and responsive performance. Backed by generous RAM and storage options, this smartphone is suitable for a wide range of tasks, from gaming to productivity. he smartphone boasts a vibrant display, which is perfect for watching videos and playing games. The AMOLED or Super AMOLED screen offers rich colors and deep blacks, creating an immersive viewing experience. The resolution ensures sharp and clear visuals."
    },
    
    
    {
        name: 'OnePlus 10T',
        brand: 'OnePlus',
        id: '28',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10t-5g.jpg',
        released: '2022, August 06',
        display: 'Fluid AMOLED, 1B colors, 120Hz, HDR10+, 6.7 inches, 108.0 cm2 (~87.9% screen-to-body ratio), 1080 x 2412 pixels, 20:9 ratio (~394 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, OxygenOS 13, Qualcomm SM8475 Snapdragon 8+ Gen 1 (4 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:16,
        main_camera:'50 MP, f/1.8, 24mm (wide), 1/1.56", 1.0µm, PDAF, OIS, 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm, 2 MP, f/2.4, (macro), Dual LED flash, HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, gyro-EIS',
        selfie_camera:'16 MP, f/2.4, 24mm (wide), 1/3", 1.0µm, HDR, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4800 mAh, non-removable, 150W wired (125W for 110V sockets)',
        price:'44990',
        network:'5G',
        battery2:4800,
        description: "The OnePlus 10 is anticipated to be a flagship Android smartphone that builds upon OnePlus's reputation for providing a high-performance, feature-rich, and well-designed device. The OnePlus 10 is likely to feature a high-quality display with a large screen size, vibrant colors, and sharp resolution. It could potentially utilize AMOLED or OLED technology for deep blacks and excellent contrast. OnePlus is known for its camera innovations, and the OnePlus 10 may feature an advanced camera system with multiple lenses for various photography scenarios. Expect high-resolution primary cameras, OnePlus has been incorporating 5G capabilities into its flagship devices."
    },
    
    {
        name: 'OnePlus 10T',
        brand: 'OnePlus',
        id: '29',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/oneplus-10t-5g.jpg',
        released: '2022, August 06',
        display: 'Fluid AMOLED, 1B colors, 120Hz, HDR10+, 6.7 inches, 108.0 cm2 (~87.9% screen-to-body ratio), 1080 x 2412 pixels, 20:9 ratio (~394 ppi density), Corning Gorilla Glass 5' ,
        platform: 'Android 12, OxygenOS 13, Qualcomm SM8475 Snapdragon 8+ Gen 1 (4 nm)',
        memory:{
            ram:8,
            rom:256,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:16,
        main_camera:'50 MP, f/1.8, 24mm (wide), 1/1.56", 1.0µm, PDAF, OIS, 8 MP, f/2.2, 120˚ (ultrawide), 1/4", 1.12µm, 2 MP, f/2.4, (macro), Dual LED flash, HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, gyro-EIS',
        selfie_camera:'16 MP, f/2.4, 24mm (wide), 1/3", 1.0µm, HDR, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4800 mAh, non-removable, 150W wired (125W for 110V sockets)',
        price:'48999',
        network:'5G',
        battery2:4800,
        description: "The OnePlus 10 is anticipated to be a flagship Android smartphone that builds upon OnePlus's reputation for providing a high-performance, feature-rich, and well-designed device. The OnePlus 10 is likely to feature a high-quality display with a large screen size, vibrant colors, and sharp resolution. It could potentially utilize AMOLED or OLED technology for deep blacks and excellent contrast. OnePlus is known for its camera innovations, and the OnePlus 10 may feature an advanced camera system with multiple lenses for various photography scenarios. Expect high-resolution primary cameras, OnePlus has been incorporating 5G capabilities into its flagship devices."
    },
    
    {
        name: 'Oppo A77s',
        brand: 'Oppo',
        id: '30',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/oppo-a77s.jpg',
        released: '2022, October 07',
        display: 'PS LCD, 90Hz, 480 nits (typ), 600 nits (HBM), 6.56 inches, 103.4 cm2 (~84.2% screen-to-body ratio), 720 x 1612 pixels, 20:9 ratio (~269 ppi density)' ,
        platform: 'Android 12, upgradable to Android 13, ColorOS 13, Qualcomm SM6225 Snapdragon 680 4G (6 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'microSDXC'
        },
        main_camera2:50,
        selfie_camera2:8,
        main_camera:'50 MP, f/1.8, 27mm (wide), PDAF, 2 MP, f/2.4, (depth), LED flash, HDR, panorama, 1080p@30fps',
        selfie_camera:'8 MP, f/2.0, 26mm (wide), Panorama, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable',
        price:'22999',
        network:'4G',
        battery2:5000,
        description: "The Oppo A77 is powered by a capable processor, ensuring smooth multitasking and efficient app performance. It may come with ample RAM and storage options to meet the needs of a wide range of users, from casual users to those who enjoy gaming and productivity tasks. The smartphone is equipped with a vibrant display that offers a decent viewing experience. The resolution ensures sharp visuals, and the colors are expected to be vivid. While it may not compete with flagship displays, it should be suitable for most multimedia and daily tasks. The Oppo A77 should offer a decent-sized battery to ensure a full day of usage. Additionally, fast charging technology is likely to be included, allowing for quick recharges. t may support 4G connectivity, which is standard for mid-range smartphones, but could also include some advanced connectivity options such as NFC for contactless payments."
    },
    
    {
        name: 'Xiaomi Poco F4 GT',
        brand: 'Xiaomi',
        id: '31',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f4-gt.jpg',
        released: '2022, April 28',
        display: 'AMOLED, 1B colors, 120Hz, HDR10+, 800 nits (HBM), 6.67 inches, 107.4 cm2 (~86.2% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass Victus' ,
        platform: 'Android 12, upgradable to Android 13, MIUI 14, Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm)',
        memory:{
            ram:12,
            rom:256,
            cardslot:'No'
        },
        main_camera2:64,
        selfie_camera2:20,
        main_camera:'64 MP, f/1.9, 26mm (wide), 1/1.73", 0.8µm, PDAF, 8 MP, f/2.2, 120˚ (ultrawide), 2 MP, f/2.4, (macro), Dual-LED flash, HDR, panorama, 4K@30/60fps, 1080p@30/60/120fps, 720p@960fps, HDR',
        selfie_camera:'20 MP, f/2.4, (wide), 1/2.0", 0.8µm, HDR, 1080p@30/60fps, 720p@120fps, HDR',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass, color spectrum Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4700 mAh, non-removable, 120W wired',
        price:'28990',
        network:'5G',
        battery2:4700,
        description: "The Xiaomi Poco F4 GT is a highly anticipated mid-range smartphone designed to offer impressive performance, 5G connectivity, and a focus on gaming and multimedia experiences. The Poco F4 GT is expected to be powered by a high-performance processor, delivering a smooth and responsive user experience. It should handle gaming and multitasking with ease, making it suitable for a wide range of tasks. Featuring a large and vibrant display, the Poco F4 GT would offer a high refresh rate screen, likely 120Hz or higher, for smoother visuals in games and when scrolling through content. The display is expected to have sharp resolution and vivid colors, As part of the Poco gaming series, this smartphone would likely come with gaming-centric features such as shoulder triggers, improved cooling technology, and optimized software for enhanced gaming performance. ",
    },
    
    {
        name: 'Realme GT2 Pro',
        brand: 'Realme',
        id: '32',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/realme-gt2-pro.jpg',
        released: '2022, January 08',
        display: 'LTPO2 AMOLED, 1B colors, 120Hz, HDR10+, 500 nits (typ), 800 nits (HBM), 1400 nits (peak), 6.7 inches, 108.0 cm2 (~88.6% screen-to-body ratio), 1440 x 3216 pixels, 20:9 ratio (~526 ppi density), Corning , ' ,
        platform: 'ndroid 12, upgradable to Android 13, Realme UI 4.0, Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:32,
        main_camera:'50 MP, f/1.8, 24mm (wide), 1/1.56", 1.0µm, multi-directional PDAF, OIS, 50 MP, f/2.2, 15mm, 150˚ (ultrawide), 1/2.76", 0.64µm, 3 MP, f/3.3, 20mm (microscope), AF, 40x magnification, Dual-LED dual-tone flash, HDR, panorama, 8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, gyro-EIS',
        selfie_camera:'32 MP, f/2.4, 26mm (wide), 1/2.74", 0.8µm, HDR, panorama, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, color spectrum',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 5000 mAh, non-removable, 65W wired',
        price:'31999',
        network:'5G',
        battery2:5000,
        description: "At the heart of the Realme GT 2 Pro is a powerful processor, likely from Qualcomm's Snapdragon series or a high-performance MediaTek chip. With ample RAM and storage, this phone is built for demanding tasks, including gaming, multitasking, and content creation, The device boasts a stunning AMOLED or OLED display with a high refresh rate, offering vibrant colors and sharp resolution. Whether you're gaming, streaming, or browsing, the visual experience is top-notch. The Realme GT 2 Pro features a sophisticated camera system, including a high-resolution primary camera, ultra-wide-angle lens, and likely a telephoto or macro lens. This setup ensures that you can capture stunning photos and videos in various scenarios. The front camera is optimized for selfies and video calls. With 5G support, the Realme GT 2 Pro offers blazing-fast internet speeds and low latency for a seamless online experience. Online gaming and 4K streaming are smooth and lag-free."
    },
    {
        name: 'Infinix Hot 12',
        brand: 'Infinix',
        id: '33',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-hot12.jpg',
        released: '2022, April 26',
        display: 'IPS LCD, 90Hz, 6.82 inches, 111.7 cm2 (~84.5% screen-to-body ratio), 720 x 1612 pixels, 20:9 ratio (~259 ppi density)' ,
        platform: 'Android 12, XOS 10.6, Mediatek MT6769Z Helio G85 (12nm)',
        memory:{
            ram:4,
            rom:64,
            cardslot:'microSDXC (dedicated slot)'
        },
        main_camera2:13,
        selfie_camera2:8,
        main_camera:'13 MP, f/1.8, (wide), AF, 2 MP, QVGA, Dual-LED flash, 1080p@30fps',
        selfie_camera:'8 MP, Dual-LED flash, 1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band',
        battery:'Li-Ion 5000 mAh, non-removable, 18W wired',
        price:'9999',
        network:'4G',
        description: "The Infinix Hot 12 is expected to be a budget-friendly smartphone designed to offer essential features for everyday users at an affordable price point. The Infinix Hot 12 is likely to be powered by an entry-level to mid-range processor, which should provide adequate performance for everyday tasks like web browsing, social media, and light gaming. It may also feature a decent amount of RAM and storage. The smartphone may include an HD+ or Full HD+ display with a reasonable screen size, offering clear visuals and adequ",
        battery2:5000
    }
];
