export const phones=[
    {
        id:1,
        img:'https://media.karousell.com/media/photos/products/2023/9/22/apple_iphone_15_pro__iphone_15_1695377265_56f897a8_progressive',
        price: '1,59,900',
        caption:'Upgrade to a newer, better iPhone'
    },
    {
        id:2,
        img:'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Galaxy_S23_Ultra_concept_dimensions_display_specs_S23_S23_plus_drdNBC_6.jpg',
        price: '1,24,999',
        caption:'Meet the new Galaxy S23 Ultra'
    }
];

export const cheapest=[
    {   
        id:'225',
        network:'	Technology	 GSM / HSPA / LTE',
        brand:'Motorola',
        name: 'Motorola Moto E13',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/motorola-moto-e13-new.jpg',
        released: '2023, February 13',
        display: 'IPS LCD Size	6.5 inches, 102.0 cm2 (~82.8% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 13 (Go edition) Chipset	Unisoc T606 (12 nm) CPU	Octa-core (2x1.6 GHz Cortex-A75 & 6x1.6 GHz Cortex-A55)',
        memory:{
            ram:'2GB',
            rom:'64GB',
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, f/2.2, (wide), 1.12µm, PDAF Features	LED flash, HDR, panorama Video	1080p@30fps',
        selfie_camera:'5 MP, f/2.4, (wide), 1/5", 1.12µm Video	1080p@30fps',
        features:'Accelerometer, proximity',
        communication:'WLAN	Wi-Fi 802.11 a/b/g/n/ac, dual-band Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable Charging	10W wired',
        description:'The Moto E13 follows the flat-frame design trend that most smartphones tend to sport these days. The frame, like the curved rear panel, is made of plastic. Motorola has tried giving the phone a premium look with a gradient frosted finish, which is something I really liked. I have the Aurora Green colour but if you want a more classic look, theres Cosmic Black and Creamy White colour options as well.',
        price:'7165',   
    },
    {   
        id:'226',
        network:'GSM / HSPA / LTE 2G bands	GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 3G bands	HSDPA 850 / 900 / 2100 4G bands	1, 3, 5, 8, 40, 41 Speed	HSPA, LTE',
        brand:'Xiaomi',
        name: 'Xiaomi Poco C51',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c51.jpg',
        released: '2023, April 13',
        display: 'IPS LCD, 400 nits (typ) Size	6.52 inches, 102.6 cm2 (~81.0% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~269 ppi density)',
        platform: 'Android 13 (Go edition), MIUI Chipset	Mediatek Helio G36 (12 nm) CPU	Octa-core (4x2.2 GHz Cortex-A53 & 4x1.7 GHz Cortex-A53)',
        memory:{
            ram:'4GB',
            rom:'64GB',
            cardslot:'NO'
        },
        main_camera:'8 MP, f/2.0, (wide)  0.08 MP (depth)  Features	Dual-LED flash, HDR  Video	1080p@30fps',
        selfie_camera:'5 MP, f/2.2  Video	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer',
        communication:'WLAN	Wi-Fi 802.11 b/g/n  Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable  Charging	10W wired',
        description:'As is often the case with entry-level smartphones, their designs tend to be very simple and theres usually not much to be said about its build quality. However, this is not the case with the Poco C51. Personally, I think the smartphone has a better design, grip, and build quality compared to its rivals. It has a polycarbonate back panel with a grainy texture which I felt was comfortable to hold even for long periods at a stretch. It offers good grip and the weight is distributed in such a way that it does not feel heavy in the hand, even though it weighs 19',
        price:'7075',   
    },
    {   
        id:'227',
        network:'GSM / HSPA / LTE',
        brand:'Samsung',
        name: 'Samsung Galaxy M12',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a12-sm-a125.jpg',
        released: '2021, February 05',
        display: 'PLS LCD, 90Hz Size	6.5 inches, 102.0 cm2 (~81.9% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 11',
        memory:{
            ram:'4GB',
            rom:'64GB',
            cardslot:'microSDXC'
        },
        main_camera:'48 MP, f/2.0, (wide), 1/2.0", 0.8µm, PDAF  5 MP, f/2.2, 123˚ (ultrawide)  2 MP, f/2.4, (macro)  2 MP, f/2.4, (depth)  Features	LED flash, panorama, HDRVideo	1080p@30fps',
        selfie_camera:'8 MP, f/2.2, (wide) Features	HDR Video	1080p@30fps',
        features:'Fingerprint (side-mounted), accelerometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 6000 mAh, non-removable Charging	15W wired',
        description:'Samsung Galaxy M12 mobile was launched on 5th February 2021. The phone comes with a 6.50-inch touchscreen display offering a resolution of 720x1600 pixels and an aspect ratio of 20:9. Samsung Galaxy M12 is powered by an octa-core processor. It comes with 3GB, 4GB, 6GB of RAM. The Samsung Galaxy M12 runs Android and is powered by a 6000mAh battery',
        price:'12000',   
    },
    {   
        id:'228',
        network:'GSM / HSPA / LTE',
        brand:'Infinix',
        name: 'Infinix Smart 7',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-smart-7.jpg',
        released: '2023, February 09',
        display: 'IPS LCD, 500 nits Size	6.6 inches, 104.6 cm2 (~84.5% screen-to-body ratio) Resolution	720 x 1612 pixels, 20:9 ratio (~267 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:'3GB',
            rom:'62GB',
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, AF 0.3 MP, (depth) Features	Dual-LED flash, HDR, panorama Video	1080p@30fps',
        selfie_camera:'	5 MP Features	LED flash Video	720p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer, proximity',
        communication:'	Wi-Fi 802.11 a/b/g/n/ac, dual-band Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh, non-removable Charging	10W wired',
        description:'The Infinix Smart 7 is available in a sole variant with 4GB of RAM and 64GB of storage. It comes in Azure Blue, Night Black and Emerald Green colour options. The smartphone is priced at Rs. 7,499 in India. The Infinix Smart 7 features a polycarbonate housing which quite frankly, is sturdy. At 207g, the smartphone definitely feels heavy. It has flat sides with the power key and volume buttons on the right and the SIM slot on the left. The Type-C charging port, microphone, speaker grille and headphone jack are all located at the bottom. ',
        price:'6599',   
    },
    {   
        id:'229',
        network:'GSM / HSPA / LTE',
        brand:'Samsung',
        name: 'Samsung Galaxy F04',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-f04-new.jpg',
        released: '2023, January 04',
        display: 'PLS LCD Size	6.5 inches, 102.0 cm2 (~81.8% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~270 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:'4GB',
            rom:'64GB',
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, f/2.2, (wide), AF 2 MP, f/2.4, (depth) Features	LED flash Video	1080p@30fps',
        selfie_camera:'5 MP, f/2.2 Video	Yes',
        features:'Accelerometer, proximity',
        communication:'Wi-Fi 802.11 b/g/n, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh',
        description:'Samsung Galaxy F04 mobile was launched on 4th January 2023. The phone comes with a 6.50-inch touchscreen display offering a resolution of 720x1600 pixels (HD+). It comes with 4GB of RAM. The Samsung Galaxy F04 is powered by a 5000mAh battery.',
        price:'6500',   
    },
    {   
        id:'230',
        network:'GSM / HSPA / LTE',
        brand:'Xiaomi',
        name: 'Xiaomi Poco C50',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-c50.jpg',
        released: '2023, January 03',
        display: 'IPS LCD, 400 nits Size	6.52 inches, 102.6 cm2 (~81.0% screen-to-body ratio) Resolution	720 x 1600 pixels, 20:9 ratio (~269 ppi density)',
        platform: 'Android 12',
        memory:{
            ram:'3GB',
            rom:'32GB',
            cardslot:'microSDXC '
        },
        main_camera:'8 MP, f/2.0, (wide) 0.08 MP (depth) Features	Dual-LED flash, HDR Video	1080p@30fps',
        selfie_camera:'	5 MP, f/2.0 Video	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer Virtual proximity sensing',
        communication:'Wi-Fi 802.11 b/g/n Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 5000 mAh',
        description:'Poco C50 mobile was launched on 3rd January 2023. The phone comes with a 6.52-inch touchscreen display offering a resolution of 700x1600 pixels. The Poco C50 runs Android Go Edition and is powered by a 5000mAh battery. The Poco C50 supports proprietary fast charging.',
        price:'6200',   
    },
    {   
        id:'231',
        network:'GSM / HSPA / LTE',
        brand:'Infinix',
        name: 'Infinix Hot 9 Play',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/infinix-hot9-play.jpg',
        released: '2020, April 09',
        display: 'IPS LCD Size	6.82 inches, 110.5 cm2 (~82.4% screen-to-body ratio) Resolution	720 x 1640 pixels (~263 ppi density)',
        platform: 'Android 9.0 Pie',
        memory:{
            ram:'3GB',
            rom:'64GB',
            cardslot:'microSDXC'
        },
        main_camera:'13 MP, (wide), 1/3.1", 1.12µm, AF  QVGA (Low light sensor) Features	Triple-LED flash, panorama, HDRVideo	1080p@30fps',
        features:'Fingerprint (rear-mounted), accelerometer, gyro, proximity, compass',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct Bluetooth	5.0, A2DP, LE',
        battery:'Li-Po 6000 mAh',
        description:'The Infinix Hot 9 was recently launched in India, along with a variant called the Hot 9 Pro. These smartphones were both priced below Rs. 10,000 at launch, but feature quad cameras and hole-punch displays. What caught my eye is the choice of processor. The Infinix Hot 9 packs in the same processor as the Infinix Hot 8, which raises a few questions. Is the Hot 9 a true upgrade, or has Infinix compromised too much to keep the price below Rs. 10,000.',
        price:'7999',   
    },
];

export const toprated=[
    {
        name: 'Samsung Galaxy S22 Ultra 5G',
        brand: 'Samsung',
        id: '10',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s22-ultra-5g.jpg',
        released: '2022, February 25',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 1750 nits (peak), 6.8 inches, 114.7 cm2 (~90.2% screen-to-body ratio), 1440 x 3088 pixels, 19.3:9 ratio (~500 ppi density), Corning Gorilla Glass Victus+ ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1,	Exynos 2200 (4 nm) - Europe',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:108,
        selfie_camera2:40,
        main_camera:'108 MP, f/1.8, 23mm (wide), 1/1.33", 0.8µm, PDAF, Laser AF, OIS 10 MP, f/4.9, 230mm (periscope telephoto), 1/3.52", 1.12µm, dual pixel PDAF, OIS, 10x optical zoom 10 MP, f/2.4, 70mm (telephoto), 1/3.52", 1.12µm, dual pixel PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF, Super Steady video ,LED flash, auto-HDR, panorama, 8K@24fps, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, stereo sound rec., gyro-EIS',
        selfie_camera:'40 MP, f/2.2, 26mm (wide), 1/2.82", 0.7µm, PDAF, Dual video call, Auto-HDR , 4K@30/60fps, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 5000 mAh, non-removable, 45W wired, PD3.0, 15W wireless, 4.5W reverse wireless',
        price:'80850',
        network:'5G',
        battery2:5000,
        description: "The S Pen fans will have little to complain about on the face of it. The S22 Ultra has the same stylus as the Note20 Ultra and, like a true Note, it has a silo for keeping the thing inside the phone - none of that carry-it-separately-until-you-inevitably-lose-it nonsense with the S21 Ultra. The significant improvements in latency also sound promising, not that the old one was bad.The camera crowd shouldn't be disappointed either. You're getting the same quad setup as the S21 Ultra (in principle, at least) and includes a couple of telephotos reaching all the way to 10x zoom, as well as an autofocusing ultrawide (that Samsung insists on keeping exclusive to the Ultra). That's in addition to the big-sensor nona-binning 108MP main camera, of course."
    },
    {
        name: 'Apple iPhone 14 Pro Max',
        brand: 'Apple',
        id: '12',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro-max-.jpg',
        released: '2022, September 16',
        display: 'LTPO Super Retina XDR OLED, 120Hz, HDR10, Dolby Vision, 1000 nits (typ), 2000 nits (HBM), 6.7 inches, 110.2 cm2 (~88.3% screen-to-body ratio), 1290 x 2796 pixels, 19.5:9 ratio (~460 ppi density), Ceramic Shield glass' ,
        platform: 'iOS 16, upgradable to iOS 17.1, Apple A16 Bionic (4 nm), Hexa-core (2x3.46 GHz Everest + 4x2.02 GHz Sawtooth), Apple GPU (5-core graphics)',
        memory:{
            ram:6,
            rom:256,
            cardslot:'No'
        },
        main_camera2:48,
        selfie_camera2:12,
        main_camera:'48 MP, f/1.8, 24mm (wide), 1/1.28", 1.22µm, dual pixel PDAF, sensor-shift OIS 12 MP, f/2.8, 77mm (telephoto), 1/3.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 120˚ (ultrawide), 1/2.55", 1.4µm, dual pixel PDAF, TOF 3D LiDAR scanner (depth), Dual-LED dual-tone flash, HDR (photo/panorama), 4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, 10-bit HDR, Dolby Vision HDR (up to 60fps), ProRes, Cinematic mode (4K@24/30fps), stereo sound rec.',
        selfie_camera:'12 MP, f/1.9, 23mm (wide), 1/3.6", PDAF, OIS SL 3D, (depth/biometrics sensor), HDR, Cinematic mode (4K@24/30fps), 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS',
        features:'Face ID, accelerometer, gyro, proximity, compass, barometer Ultra Wideband (UWB) support Emergency SOS via satellite (SMS sending/receiving)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, hotspot',
        battery:'Li-Ion 4323 mAh, non-removable (16.68 Wh), Wired, PD2.0, 50% in 30 min (advertised) 15W wireless (MagSafe) 7.5W wireless (Qi)',
        price:'149900',
        network:'5G',
        battery2:4342,
        description:"The best iPhone ever, version 2022, size XL - we have the iPhone 14 Pro Max. The list of novelties this year includes the notch morphing into a pill, the introduction of an Always-On display, and an all-new primary camera - and while you can get all of that on the 14 Pro, the extra screen estate and longevity coupled with the Max's 'ultimate' status mean it has a market niche of its own.Late to yet another party, Apple finally joins virtually every other manufacturer and introduces a camera with a Quad Bayer type sensor - the specs on the 48MP main unit.In a similar vein is the Always-On display - a software feature only made possible now in Apple's world thanks to LTPO displays being able to ramp down to 1Hz refresh rate."
    },
    {
        name: 'Google Pixel 7',
        brand: 'Google',
        id: '23',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel7-new.jpg',
        released: '2022, October 13',
        display: 'AMOLED, 90Hz, HDR10+, 1000 nits (HBM), 1400 nits (peak), 6.3 inches, 96.7 cm2 (~84.9% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~416 ppi density), Corning Gorilla Glass Victus' ,
        platform: 'Android 13, upgradable to Android 14, Google Tensor G2 (5 nm)',
        memory:{
            ram:8,
            rom:128,
            cardslot:'No'
        },
        main_camera2:50,
        selfie_camera2:10.8,
        main_camera:'50 MP, f/1.9, 25mm (wide), 1/1.31", 1.2µm, dual pixel PDAF, Laser AF, OIS, 12 MP, f/2.2, 114˚ (ultrawide), 1/2.9", 1.25µm, Dual-LED flash, Pixel Shift, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/120/240fps; gyro-EIS, OIS, 10-bit HDR',
        selfie_camera:'10.8 MP, f/2.2, 21mm (ultrawide), 1/3.1", 1.22µm, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, tri-band, Wi-Fi Direct',
        battery:'Li-Ion 4355 mAh, non-removable, 20W wired',
        price:'42998',
        network:'5G',
        battery2:4355,
        description:"On the surface, the Pixel 7 and 7 Pro aren't much different from the Pixel 6 series while introducing some small but notable upgrades. Maybe that's part of the reason why we think the 7th generation has a good chance of winning over new fans around the globe. Although 'the globe' might not be the best choice of words given the limited availability as usual.The Pixel 7 offers a few key improvements over its predecessor, the Pixel 6. It's now running on an improved Google Tensor G2 chip with better AI capabilities, Gorilla Glass Victus build all-around, a better selfie camera and a smaller display. As a result, the Pixel 7 is slightly smaller than the Pixel 6, which is a clear indication that Google is aiming for the compact flagship niche. And although smaller, the Pixel 7's display is considerably brighter.The camera setup on the back remains unchanged. We've got a big 50MP sensor doing the heavy lifting and a 12MP ultrawide camera helping out. There's still no telephoto camera, but to be fair, that's a rare find in the compact flagship class. Still, Google promises better image processing and improved overall camera quality through machine learning algorithms and better ISP capabilities."
    },
    {
        name: 'Apple iPhone 14',
        brand: 'Apple',
        id: '20',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg',
        released: '2022, September 16',
        display: 'Super Retina XDR OLED, HDR10, Dolby Vision, 800 nits (HBM), 1200 nits (peak), 6.1 inches, 90.2 cm2 (~86.0% screen-to-body ratio), 1170 x 2532 pixels, 19.5:9 ratio (~460 ppi density), Ceramic Shield glass' ,
        platform: 'iOS 16, upgradable to iOS 17.1, Apple A15 Bionic (5 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:12,
        main_camera:'12 MP, f/1.5, 26mm (wide), 1/1.7", 1.9µm, dual pixel PDAF, sensor-shift , 12 MP, f/2.4, 13mm, 120˚ (ultrawide), Dual-LED dual-tone flash, HDR (photo/panorama), 4K@24/25/30/60fps, 1080p@25/30/60/120/240fps, HDR, Dolby Vision HDR (up to 60fps), Cinematic mode (4K@30fps), stereo sound rec.',
        selfie_camera:'12 MP, f/1.9, 23mm (wide), 1/3.6", PDAF, SL 3D, (depth/biometrics sensor), HDR, Cinematic mode (4K@30fps), 4K@24/25/30/60fps, 1080p@25/30/60/120fps, gyro-EIS',
        features:'Face ID, accelerometer, gyro, proximity, compass, barometer, Ultra Wideband (UWB) support, Emergency SOS via satellite (SMS sending/receiving)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 3279 mAh, non-removable (12.68 Wh), Wired, PD2.0, 50% in 30 min (advertised)',
        price:'56998',
        battery2:3279,
        network:'5G',
        description:"The new iPhone 14 sort of fits into this category of product. Just sort of, though, since Apple has redesigned the internals quite a bit to facilitate easier repairability, among other things. Plus, you do get new cameras and a few other new features. Externally, though, the iPhone 14 is essentially the same as the iPhone 13, and so is the core experience these devices offer. If Apple still did 's' models in their naming scheme, the iPhone 14 would probably be the iPhone 13s.The vanilla iPhone 14 even starts at $799 in the US, just like its predecessor, so it occupies the same segment and fills the same shoes if it were. That said, most markets outside the US have a price hike on the iPhone 14, and the iPhone 13 has come down in price since its launch. Even in the US, it is now $100 or so cheaper"
    },
    {
        name: 'Samsung Galaxy S21 FE 5G',
        brand: 'Samsung',
        id: '5',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s21-fe-5g.jpg',
        released: '2022, January 07',
        display: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 6.4 inches, 100.5 cm2 (~86.7% screen-to-body ratio), 080 x 2340 pixels, 19.5:9 ratio (~403 ppi density), orning Gorilla Glass Victus ' ,
        platform: 'Android 12, upgradable to Android 13, One UI 5.1, Qualcomm SM8350 Snapdragon 888 5G (5 nm) - Version 1',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12,
        selfie_camera2:32,
        main_camera:'12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS 8 MP, f/2.4, 76mm (telephoto), 1/4.5", 1.0µm, PDAF, OIS, 3x optical zoom 12 MP, f/2.2, 13mm, 123˚ (ultrawide), 1/3.0", 1.12µm LED flash, auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/240fps, 720p@960fps, HDR10+, gyro-EIS',
        selfie_camera:'32 MP, f/2.2, 26mm (wide), 1/2.74", 0.8µm, HDR , 4K@30/60fps, 1080p@30/60fps, gyro-EIS',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass Samsung DeX (desktop experience support)',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Ion 4500 mAh, non-removable,25W wired',
        price:'32860',
        battery2:4500,
        network:'5G',
        description:"Samsung has focused on three fan-favorite features for this Fan Edition - display, performance, and camera. And it has tried to give more of those for less, a job best suited for the flagship-killer kind. We surely are not calling it that, but the S21 FE does sound quite promising as an almost-there-flagship.The Galaxy S21 FE updates the display with the S21's screen panel. It offers a 6.4-inch Dynamic AMOLED 2X with native HDR10+ support and a 120Hz refresh rate. The Galaxy S20 FE's Super AMOLED had no HDR10 capabilities at launch, which was disappointing back then, but these were enabled later in 2021.Then there is performance - quite expectedly, the Galaxy S21 FE offers the same hardware as the rest of the S21 series - either the Snapdragon 888, or the Exynos 2100 chipset. But the chipset segmentation is reversed here - the international model is the one with the Snapdragon, while Samsung's silicon is limited to Australia (so far)."
    },
    {
        name: 'Xiaomi Poco F4 GT',
        brand: 'Xiaomi',
        id: '31',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/xiaomi-poco-f4-gt.jpg',
        released: '2022, April 28',
        display: 'AMOLED, 1B colors, 120Hz, HDR10+, 800 nits (HBM), 6.67 inches, 107.4 cm2 (~86.2% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~395 ppi density), Corning Gorilla Glass Victus' ,
        platform: 'Android 12, upgradable to Android 13, MIUI 14, Qualcomm SM8450 Snapdragon 8 Gen 1 (4 nm)',
        memory:{
            ram:12,
            rom:256,
            cardslot:'No'
        },
        main_camera2:64,
        selfie_camera2:20,
        main_camera:'64 MP, f/1.9, 26mm (wide), 1/1.73", 0.8µm, PDAF, 8 MP, f/2.2, 120˚ (ultrawide), 2 MP, f/2.4, (macro), Dual-LED flash, HDR, panorama, 4K@30/60fps, 1080p@30/60/120fps, 720p@960fps, HDR',
        selfie_camera:'20 MP, f/2.4, (wide), 1/2.0", 0.8µm, HDR, 1080p@30/60fps, 720p@120fps, HDR',
        features:'Fingerprint (side-mounted), accelerometer, gyro, compass, color spectrum Virtual proximity sensing',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4700 mAh, non-removable, 120W wired',
        price:'28990',
        network:'5G',
        battery2:4700,
        description: "The Xiaomi Poco F4 GT is a highly anticipated mid-range smartphone designed to offer impressive performance, 5G connectivity, and a focus on gaming and multimedia experiences. The Poco F4 GT is expected to be powered by a high-performance processor, delivering a smooth and responsive user experience. It should handle gaming and multitasking with ease, making it suitable for a wide range of tasks. Featuring a large and vibrant display, the Poco F4 GT would offer a high refresh rate screen, likely 120Hz or higher, for smoother visuals in games and when scrolling through content. The display is expected to have sharp resolution and vivid colors, As part of the Poco gaming series, this smartphone would likely come with gaming-centric features such as shoulder triggers, improved cooling technology, and optimized software for enhanced gaming performance. ",
    },
    {
        name: 'Google Pixel 6a',
        brand: 'Google',
        id: '19',
        image: 'https://fdn2.gsmarena.com/vv/bigpic/google-pixel-6a.jpg',
        released: '2022, July 21',
        display: 'OLED, HDR, 6.1 inches, 90.7 cm2 (~83.0% screen-to-body ratio), 1080 x 2400 pixels, 20:9 ratio (~429 ppi density), Corning Gorilla Glass 3' ,
        platform: 'Android 12, upgradable to Android 14, Google Tensor (5 nm)',
        memory:{
            ram:6,
            rom:128,
            cardslot:'No'
        },
        main_camera2:12.2,
        selfie_camera2:8,
        main_camera:'12.2 MP, f/1.7, 27mm, (wide), 1/2.55", 1.4µm, dual pixel PDAF, OIS, 12 MP, f/2.2, 17mm, 114˚ (ultrawide), 1.25µm, Dual-LED flash, Pixel Shift, Auto-HDR, panorama, 4K@30/60fps, 1080p@30/60/120/240fps; gyro-EIS, OIS',
        selfie_camera:'8 MP, f/2.0, 24mm (wide), 1.12µm, Auto-HDR, panorama, 1080p@30fps',
        features:'Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, barometer',
        communication:'Wi-Fi 802.11 a/b/g/n/ac/6e, dual-band, Wi-Fi Direct',
        battery:'Li-Po 4410 mAh, non-removable, 18W wired, PD3.0',
        price:'30998',
        network:'5G',
        battery2:4410,
        description:"For the past three years Google has attempted to repackage its flagships phones into A Series phones that capture the Pixel essence at a far more attractive price point. The Google Pixel 6a even got the same custom Tensor chipset as the more expensive Pixels, further sweetening the deal.The Pixel 6a is notably compact with its 6.1-inch OLED screen and far lighter at 178g (vs 207g for the Pixel 6). It perfectly captures the design, look, and feel of the more expensive Pixel 6 and Pixel 6 Pro while strategically shaving costs down in places that doesn't have a big impact on usability.Google Pixel 6a review.The Pixel 6a doesn't have a charger in the box - a change that came with the Pixel 6 and 6 Pro. Google also axed the headphone jack in a first for the Pixel A Series.The Pixel 6a's camera is the tried-and-true Sony IMX 363 sensor, the same one that's been used since the Google Pixel 2. Google only stopped using it on its premium Pixels this year, so we probably shouldn't be surprised that the 6a didn't get a different sensor. And we might still see the aging sensor up its performance when paired with the Google Tensor."
    },
];


